### ISSUE TITLE
Not work for devices that not support end Key (keycode: 13)

### ISSUE THREAD

**Issue by anansaleh** [noomerzx/vue-barcode-scanner#9] opened 2017-07-19 11:00 UTC
Thanks for your plug ins. It’s not work for devices that not support end Key (keycode: 13). I stoved the problem by making some changes in your code. here what I do

1. I create local value  timerId
2. I cut the code from your function onInputScanned lines (77 – 88) and replace it with triggerBarcode();
3. I create function triggerBarcode() and paste the code inside it

The final my new change are:

`
	let timerId = -1;

    function triggerBarcode() {

      if (timerId > -1)
        clearTimeout(timerId);

      timerId=-1;

      // scanner is done and trigger Enter/Tab then clear barcode and play the sound if it's set as true
      attributes.callback(attributes.barcode)
      // backup the barcode
      attributes.previousCode = attributes.barcode
      // clear textbox
      attributes.barcode = ''
      // clear pressedTime
      attributes.pressedTime = []
      // trigger sound
      if (attributes.setting.sound) {
        triggerSound()
      }
    }

    function onInputScanned (event) {
      // ignore other keydown event that is not a TAB, so there are no duplicate keys
      if (event.type === 'keydown' && event.keyCode != 9 ) {
        return
      }

      if (checkInputElapsedTime(Date.now())) {

        if ((event.keyCode === 13 || event.keyCode === 9) && attributes.barcode !== '') {

          triggerBarcode();
          // prevent TAB navigation for scanner
          if (event.keyCode === 9) {
            event.preventDefault()
          }
        } else {
          //reset timer
          if (timerId > -1)
            clearTimeout(timerId);
          timerId = setTimeout(triggerBarcode, attributes.setting.scannerSensitivity);

          // scan and validate each charactor
          attributes.barcode += event.key
        }
      }
    }`

So please check it if it good to use

**Comment by pangaunn** [comment] 2017-07-23 12:49
Please create pull request for this change, Thanks

**Comment by anansaleh** [comment] 2017-07-24 08:43
Please give me permission
Error message
remote: Permission to noomerzx/vue-barcode-scanner.git denied to anansaleh.


Anan Saleh
===================================
IT Manager – Software Engineering & Developing
Phone: (+30) 2310 700 027 - 6979 222 181

**Comment by noomerzx** [comment] 2017-07-24 09:31
I'm not sure what the problem of this issue the keycode 13 is "Enter" key right ? almost scanner use this for the last key input and I've tested it's work find. So it'll be great if you can give me some more information about the problem and may be some scenario.

Thx so much to inform this, I got your request and I'll take a look then make some update as soon as possible.

**Comment by anansaleh** [comment] 2017-07-24 14:18
Thank u for replay. The problem is when I test it with scanner that has the
last key input (13) “Enter” its work perfect, but when I test it with
scanner that not use last key (13) its not work.

For example lets say that you have two Barcode

b1=1111111111111

b2=222222222222

and you scan first b1 and then b2 so as in your example code


onBarcodeScanned (barcode) {
	x=  barcode
}


I have the following result

in the first situation

x= 222222222222

but in the second


x= 1111111111111222222222222

that mean the barcode not initialize in the second situation.

Anan Saleh
===================================
IT Manager – Software Engineering & Developing
Phone: (+30) 2310 700 027 - 6979 222 181

**Comment by noomerzx** [comment] 2017-09-13 10:57
Sorry for a extremely late T3T I really busy and forgot about this issue, So I'm really sorry but I've just reviewed your code on pull request and I was confused that all your whole code is in request description but the 2 included committed is just change the version and some 1 line changed. and those 2 change not fixed your problem. So I wanna merge you in my master but you need to committed your change in request

**Closed as completed** 2018-01-04 04:34 UTC

**Comment by bryantbj** [comment] 2019-03-07 22:27
I realize this is a closed issue, but I'm facing the same problem @anansaleh described. I think the problem is some scanners do not send `keycode 13` as the final character to signify the end of a character sequence. In this case, the callback is never fired.

@anansaleh's solution is basically:
- if `keycode` is 13 or 9 and the buffer is not empty, execute the callback
- else, execute the callback after `attributes.scannerSensitivity` ms has elapsed.
- each invocation resets the `setTimeout` until the last keypress event is received.

I'm happy to write a pull request to address this issue.

**Comment by bryantbj** [comment] 2019-03-08 22:49
@noomerzx I have created a PR that addresses this issue. Please review at your earliest convenience.
